package edu.hood.cs.it530.findyourdoctor;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kisna' at '11/20/16 11:15 AM' with Gradle 2.14.1
 *
 * @author kisna, @date 11/20/16 11:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
